services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    networks:
      app-network:
    depends_on:
      - banco
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./composer.json:/var/www/html/composer.json
  banco:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: desafiocontatos
    ports:
      - "5433:5432"
    networks:
      app-network:
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge